# target1, target2 は docker-compose.yml の hostname 設定に対応している
# Docker の ansible-net ネットワーク内でこのホスト名が名前解決される
[targets]
target1
target2

[webservers]
target1

[dbservers]
target2

[targets:vars]
ansible_user=ansible
ansible_password=ansible
ansible_become_password=ansible
ansible_python_interpreter=/usr/bin/python3
